services:
  - type: web
    name: tripmate-backend
    runtime: docker
    dockerfilePath: ./tripmate-backend/Dockerfile
    dockerContext: ./tripmate-backend
    plan: free
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: CORS_ORIGINS
        sync: false
